examples/bar.rs, lvgl/src/widgets/bar.rs
Possible to set styles, for the various bar components (background and indicator), as outlined in the [lvgl documentation](https://docs.lvgl.io/en/html/object-types/bar.html#_CPPv4Ut7_anon_41).
=> Set style for different bar components

lvgl-codegen/Cargo.toml, lvgl-sys/Cargo.toml, lvgl/Cargo.toml
- Removes the dependency on `alloc` crate
- Simplify examples by removing the use of threads
=> Release 0.4.0

lvgl-sys/build.rs
This makes it possible to compile `lvgl-rs` to WASM using the target `wasm32-unknown-emscripten`.
=> Compile to WASM using Emscripten

README.md
At least in my case it was necessary to install libsdl (SDL2) before I was able to compile the demos on my Mac. I added a hint to the README in order to help other developers that stumble upon that problem.
Fixes #35
=> Update README: Added a hint to install SDL2 before running the demos on macOS

lvgl-codegen/src/lib.rs
This PR fixes the compile error that happens whenever you try and use this crate.
=> Fix compiler error when running the examples

README.md
Without that, I got the following error from cargo:
```
error: target `demo` in package `lvgl` requires the features: `alloc`
Consider enabling them by passing, e.g., `--features="alloc"`
```
=> Add --features="alloc" to run demo

lvgl/src/lv_core/style.rs, lvgl/src/mem.rs
This allows for re-using the same style for multiple widgets, as the `Widget::add_style` method needs to take ownership of the `Style` object.
Since `Style` uses a `Box` internally, it was also necessary to implement `Clone` for that too.
=> Implement Clone for Style

lvgl/src/ui.rs
This PR adds support for changing the current screen via the `load_scr` function based on the `lv_disp_load_scr` from lvgl.
Example usage:
```rust
// Default screen
let mut def_screen = ui.scr_act()?;
// Extra screen
let mut screen = Obj::default();
// ... Add style and widgets to each screen
// Load the extra screen
ui.load_scr(&mut screen);
// Change back to def_screen
ui.load_scr(&mut def_screen);
```
=> Add support for switching screens

lvgl/Cargo.toml
Suggested solution for issue #58. More Details can be found there.
=> Disabled arc feature in cstr_core to add compatibility for targets without support for atomic operations

.github/workflows/rust.yml
Make all tests run single threaded. We need that because some things we check in the tests cannot support concurrency.
=> Run tests single threaded

examples/Cargo.toml, examples/arc.rs, examples/bar.rs, examples/button_click.rs, examples/demo.rs, examples/gauge.rs, examples/simple.rs, lvgl/src/input_device.rs, lvgl/src/input_device/generic.rs, lvgl/src/input_device/mod.rs, lvgl/src/input_device/pointer.rs, lvgl/src/lib.rs, lvgl/src/mem.rs, lvgl/src/support.rs, lvgl/src/ui.rs
Rebased `indev` onto the current `master` and squashed/reordered relevant commits. Some outstanding questions I have before marking this as ready:
- LVGL supports `POINTER`, `KEYBOARD`, `ENCODER`, and `BUTTON` input device types. Should I implement all 4 before merging or just flesh out and/or test functionality for pointer devices?
- I'm considering making bindings to [lv-drivers](https://github.com/lvgl/lv_drivers) for input devices. Is this within scope for input device support or should I make it a separate PR later? Assuming in scope, how should I implement it (perhaps `lvgl-sys-drivers` and `lvgl-drivers` subcrates)?
=> Basic support for input devices

LICENSE
Bump license copyright year to 2023. It irked me so now I'll fix it :)
=> Bump license

Cross.toml, lvgl-sys/build.rs
When building via `cross` as in #53 certain environment variables need to be forwarded. Also, SDL2 will now be linked in by default if the `LVGL_LINK` variable is unset as it's enabled by default in the `lv_drv_conf.h` that we vendor.
=> Basic `cross` infrastructure and fixups

lvgl/src/display.rs
The dereferencing of `disp_drv` in [display.rs:330](https://github.com/rafaelcaricio/lvgl-rs/blob/2e2fb1c294ebc7376b92bf4cedb63d1d59ebcba2/lvgl/src/display.rs#L330) would lead to a move and set everything behind the old pointer to null. Simply moving back before the pointer is reused fixes this.
This took at least 4 hours for me to figure out. I hate pointers.
=> Eliminate UB around move semantics in display logic

examples/app.rs, examples/arc.rs, examples/bar.rs, examples/button_click.rs, examples/demo.rs, examples/meter.rs, examples/sdl.rs, lvgl/Cargo.toml, lvgl/src/display.rs, lvgl/src/drivers/mod.rs, lvgl/src/font/generic.rs, lvgl/src/font/mod.rs, lvgl/src/input_device/mod.rs, lvgl/src/lib.rs, lvgl/src/lv_core/style.rs
As discussed in #69, the current API can cause UB if not used properly. The option of using `static_init` to auto-initialize was agreed on, though I opted for [`ctor`](https://crates.io/crates/ctor) since it does the same thing but seems better-maintained. I added a feature also to gate disabling this behaviour, along with a huge disclaimer as to why it shouldn't be used.
Closes #69
=> Auto-initialize LVGL

examples/include/lv_conf.h, examples/rust_timer.rs, lvgl-sys/Cargo.toml, lvgl-sys/build.rs, lvgl-sys/vendor/include/timer/rs_timer.h, lvgl/Cargo.toml, lvgl/src/drivers/lv_drv_input.rs, lvgl/src/drivers/mod.rs, lvgl/src/functions.rs, lvgl/src/input_device/generic.rs, lvgl/src/input_device/mod.rs, lvgl/src/input_device/pointer.rs, lvgl/src/lib.rs, lvgl/src/lv_core/style.rs, lvgl/src/timer.rs
Implements a new trait, `LvClock`, which can be implemented to define a clock. I adapted the `bar` example so far but I'll make it its own example (+ write docs), and also I need to fix a bunch of compiler warnings. But, it's already functional :D
Closes #25
=> Allow LVGL timer to be set from Rust

lvgl/src/lv_core/obj.rs, lvgl/src/widgets/mod.rs
Add more docs and comment out the inclusion of the `arc.rs` module.
Since #67 no special functionality is implemented on the `Arc` widget anymore, so it will no longer be compiled in. I'm keeping it in the source since we might want to implement new functionality in the future.
=> More documentation and dead code disabling

lvgl/src/display.rs
This was a lovely (awful) issue to fix, and was actually the core issue underpinning #74. When implementing the `lv_disp_t`, the LVGL docs specify that the driver object *must* be the [first member of the struct](https://docs.lvgl.io/latest/en/html/porting/display.html#_CPPv49lv_disp_t). In #67 I changed the struct we have here to also hold the buffer, as this simplified both the API and the internal logic. However, I was *not* aware of the requirement re: struct layout, and Rust [doesn't actually guarantee any specific type layout](https://doc.rust-lang.org/reference/type-layout.html#the-default-representation); so, on certain buffer sizes, the compiler was putting the buffer before the driver.
On the bright side, all this segfault chasing has quadrupled my productivity with `lldb`.
=> Fix segfault on certain buffer sizes

CHANGELOG.md, lvgl-codegen/Cargo.toml, lvgl-sys/Cargo.toml, lvgl/Cargo.toml
Need to exclude things from the `lvgl-sys` for `crates.io` to be happy. Requires a version bump...
=> crates.io fixup

lvgl/src/input_device/encoder.rs, lvgl/src/input_device/generic.rs, lvgl/src/input_device/pointer.rs, lvgl/src/lv_core/group.rs, lvgl/src/lv_core/mod.rs
Allow creation of `Group`s for use with encoders (and keypads when those are added)
=> Group support

.github/workflows/rust.yml, lvgl/src/display.rs
Partially remedies #103; ~~crate should now automatically determine the correct colourspace to use~~ small mistake fixed.
~~Should we expose this type publicly also?~~
=> Fix non-16 bit colourspace issue

lvgl/Cargo.toml
This is a very small delta to fix an issue I ran into with different versions of embedded-graphics being pulled in by other crates
* Bump embedded-graphics version to latest release 0.8.0
* Bump embedded-graphics-emulator to corresponding release 0.5.0
Tested with the demo example and X11
```
Running `target/debug/examples/demo`
[Info]  (0.000, +0)      lv_init: begin         (in lv_obj.c line #102)
[Info]  (0.000, +0)      lv_obj_create: begin   (in lv_obj.c line #206)
[Info]  (0.000, +0)      lv_obj_create: begin   (in lv_obj.c line #206)
[Info]  (0.000, +0)      lv_obj_create: begin   (in lv_obj.c line #206)
Before all widgets: lv_mem_monitor_t { total_size: 1048576, free_cnt: 1, free_size: 923848, free_biggest_size: 923848, used_cnt: 74, max_used: 118580, used_pct: 12, frag_pct: 0 } …
```
=> Bump embedded-graphics version. Tested with example under X11

lvgl/Cargo.toml, lvgl/src/display.rs, lvgl/src/lib.rs, lvgl/src/support.rs
This feature is nightly-only so I was hesitant to add but since we already have a `nightly` feature I figured it's okay. Will make working with e.g. `anyhow` as a consumer a lot simpler.
=> Implement the `Error` trait for our internal error types

Cargo.toml, lvgl-codegen/src/lib.rs, lvgl-sys/src/lib.rs, lvgl/src/display.rs, lvgl/src/functions.rs, lvgl/src/lib.rs, lvgl/src/lv_core/obj.rs, lvgl/src/lv_core/screen.rs, lvgl/src/lv_core/style.rs, lvgl/src/misc/anim.rs, lvgl/src/support.rs, lvgl/src/widgets/arc.rs, lvgl/src/widgets/bar.rs, lvgl/src/widgets/keyboard.rs, lvgl/src/widgets/label.rs, lvgl/src/widgets/slider.rs, lvgl/src/widgets/table.rs
Begins work for tracking object and style lifetime so we can eventually auto-drop them. Currently only minimal work done, styling lifetime addition still not started.
Closes #107, closes #110, begins work on #111 and #140
=> Lifetime tracking for objects and styles

examples/sdl.rs, lvgl-codegen/src/lib.rs, lvgl/src/display.rs, lvgl/src/functions.rs, lvgl/src/lv_core/group.rs, lvgl/src/lv_core/obj.rs, lvgl/src/lv_core/screen.rs, lvgl/src/misc/anim.rs, lvgl/src/widgets/arc.rs, lvgl/src/widgets/bar.rs, lvgl/src/widgets/keyboard.rs, lvgl/src/widgets/label.rs, lvgl/src/widgets/slider.rs, lvgl/src/widgets/table.rs
=> `<T as NativeObject>::raw()` infallible, `Obj` store `NonNull` pointers

lvgl-sys/build.rs
Before fix:
`"-I" "/" "-I" "home" "-I" "jmjoy" "-I" "workspace" "-I" "rust" "-I" "lv_binding_rust" "-I" "fonts"`
After fix:
`"-I" "/home/jmjoy/workspace/rust/lv_binding_rust/fonts"`
=> Fix including fonts when building lvgl-sys

lvgl-sys/src/string_impl.rs
Currently `strcmp` calls `strncmp` with `usize::MAX` which causes a panic due to the use of `from_raw_parts`.
```
thread 'main' panicked at library/core/src/panicking.rs:155:5:
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
```
This issue is triggered, for instance, when trying to create a keyboard widget.
This PR changes the implementation of `strncmp` to iterate over the strings up to the specified size but stopping on null bytes.
=> Fix strncmp to not blindly read past string end

lvgl-sys/build.rs
Allow passing more flags beyond what rust build system can pass.
=> feat: accept additional cflags from LVGL_CFLAGS env var

lvgl-sys/build.rs
This shall fix original PR #173 and close PR #174.
=> fix: empty define when LVGL_CFLAGS variable is not passed

examples/demo.rs
Fix compile errors to build examples/demo.rs.
=> Able to compile examples/demo.rs

lvgl/Cargo.toml, lvgl/src/lib.rs
This feature is necessary when `LV_MEM_CUSTOM=1` because `lv_deinit()` is not defined in this scenario :
```
error[E0425]: cannot find function `lv_deinit` in crate `lvgl_sys`
--> /home/alix_anneraud/.cargo/git/checkouts/lv_binding_rust-d86feb7597e107b7/9829aef/lvgl/src/lib.rs:103:23
|
103  |             lvgl_sys::lv_deinit();
|                       ^^^^^^^^^ help: a function with a similar name exists: `lv_init`
|
::: /home/alix_anneraud/Git/Personnel/Xila/New-Code/target/debug/build/lvgl-sys-927f327e46b48320/out/bindings.rs:7701:5
|
7701 |     pub fn lv_init();
|     ---------------- similarly named function `lv_init` defined here
For more information about this error, try `rustc --explain E0425`.
error: could not compile `lvgl` (lib) due to 1 previous error
```
=> Add custom allocator feature

README.md
Added information about safe and unsafe bindings for clarification.
=> Update README with notes about safe and unsafe bindings

examples/demo.rs
Fixes some unused warnings on the `demo.rs` file.
=> demo: Cleanup warnings

lvgl-sys/Cargo.toml, lvgl/Cargo.toml, lvgl/src/functions.rs
lv_tick_inc function is available only when default (non-custom) timer implementation is used.
This patch fixes building the bindings in that case.
=> fix: gate tick_inc function by feature custom_timer
