lvgl/lv_binding_rust

- README.md
- examples/demo/README.md
When I first encountered this awesome project, I assumed that I would need to buy some hardware in order to try it. But after some digging I realized that the `demo` example runs in a simulator. So I tried to explain this a little better, and also mention that a git submodule needs to be installed.
> Explain that example runs in a simulator

- README.md
currently if we try to build juste after clone, we get a file not found exception
> improve demo documentation

- lvgl/src/support.rs
> Expose RGB values from Color

- README.md
- lvgl-sys/build.rs
> Fix build in Docs.rs

- lvgl-codegen/Cargo.toml
- lvgl-codegen/src/lib.rs
- lvgl-sys/Cargo.toml
- lvgl-sys/build.rs
- lvgl/Cargo.toml
- lvgl/src/support.rs
- lvgl/src/ui.rs
Upgrade the vendored version of LVGL C library to the latest v7.10.1 version. I've also updated all other dependencies to their latest version.
> Upgrade LVGL vendored to v7.10.1

- examples/Cargo.toml
- examples/demo.rs
- lvgl-codegen/Cargo.toml
- lvgl-sys/Cargo.toml
- lvgl-sys/build.rs
- lvgl/src/mem.rs
- lvgl/src/ui.rs
- Upgrades some dependencies;
- Clean up `demo.rs`
- Improve testing of custom `Box`
> Upgrade to lvgl v7.10.1

- lvgl-sys/Cargo.toml
- lvgl-sys/build.rs
- lvgl/Cargo.toml
If you don't want/need a custom config, just use this one.
> add use-vendored-config feature

- lvgl/src/lv_core/mod.rs
- lvgl/src/ui.rs
Latest git release doesn't compile. This is a super simple change that should fix it.
> Fix building project

- lvgl-codegen/Cargo.toml
- lvgl-sys/Cargo.toml
- lvgl/Cargo.toml
- lvgl/src/allocator.rs
- lvgl/src/mem.rs
Bumps all dependencies for the crates. Also required doing (tiny) code changes for it to compile.
> Bump dependencies

- README.md
- lvgl/Cargo.toml
- lvgl/src/lib.rs
- lvgl/src/mem.rs
Because we just can't have nice things. Follow-up on discussion in #79
> More docs about auto-initialization

- CHANGELOG.md
- examples/README.md
- lvgl-codegen/Cargo.toml
- lvgl-sys/Cargo.toml
- lvgl/Cargo.toml
🥳 
I don't think I have rights to push a new release (or if so I'm not sure how) but this bumps version to 0.6
> Version 0.6.0

- examples/button_click.rs
- lvgl-sys/build.rs
- lvgl/src/input_device/encoder.rs
- lvgl/src/input_device/generic.rs
- lvgl/src/input_device/mod.rs
- lvgl/src/lib.rs
- lvgl/src/point.rs
- lvgl/src/support.rs
Should I add tests (for it and pointers) before merging?
> Support encoder input devices

- lvgl/src/input_device/encoder.rs
Accidentally left in temp values. oops
> Fix encoder values

- examples/button_click.rs
- examples/sdl.rs
> Fix `button_click` example

- lvgl/src/support.rs
- lvgl/src/widgets/arc.rs
- lvgl/src/widgets/bar.rs
- lvgl/src/widgets/mod.rs
- lvgl/src/widgets/slider.rs
Adds some basic methods for sliders.
Closes #119
> Basic `Slider` support

- lvgl/src/widgets/arc.rs
- lvgl/src/widgets/bar.rs
- lvgl/src/widgets/mod.rs
- lvgl/src/widgets/slider.rs
- lvgl/src/widgets/table.rs
Adds some more methods needed for using this widget
Closes #122
> Flesh out `Table` widget

- lvgl/src/support.rs
> Handle more events

- lvgl-codegen/Cargo.toml
- lvgl-sys/Cargo.toml
- lvgl-sys/build.rs
- lvgl/Cargo.toml
- lvgl/src/misc/area.rs
- lvgl/src/misc/mod.rs
- lvgl/src/support.rs
> Add helper functions for coord types, update deps

- lvgl/src/support.rs
- lvgl/src/widgets/label.rs
> Label long-mode functionality

- lvgl/src/lib.rs
- lvgl/src/lv_core/style.rs
- lvgl/src/misc/area.rs
- lvgl/src/support.rs
- lvgl/src/widgets/label.rs
> More infrastructure for `Flex` layout

- lvgl/src/lv_core/obj.rs
- lvgl/src/lv_core/screen.rs
- lvgl/src/lv_core/style.rs
Minimal implementation of Debug for Obj, Style and Screen
> Impl Debug

- README.md
- examples/animation.rs
- examples/bar.rs
- examples/rust_timer.rs
- lvgl/Cargo.toml
- lvgl/src/display.rs
- lvgl/src/drivers/lv_drv_display.rs
- lvgl/src/drivers/lv_drv_input.rs
- lvgl/src/functions.rs
- lvgl/src/input_device/encoder.rs
- lvgl/src/input_device/pointer.rs
- lvgl/src/lib.rs
- lvgl/src/lv_core/group.rs
- lvgl/src/lv_core/obj.rs
- lvgl/src/lv_core/screen.rs
- lvgl/src/mem.rs
- lvgl/src/misc/anim.rs
- lvgl/src/misc/mod.rs
- lvgl/src/support.rs
- lvgl/src/widgets/bar.rs
- lvgl/src/widgets/slider.rs
Because this was simpler to work on than image support.
TODO:
> Animation support

- lvgl/src/lv_core/style.rs
Closes #136
Not all cases currently covered, can be in the future though as requested
> Implement a skeleton for `style.get_prop()`

- lvgl/src/lib.rs
> lvgl: reexport sys crate

- examples/animation.rs
- examples/arc.rs
- examples/bar.rs
- examples/button_click.rs
Fix examples compilation (might not be rusty enough):
- arc
- animation
- bar. I had to comment out `lvgl::event_send` to make this example compile and run.
- button_click
Needs #177
> Fix examples
